# Base application services
# This file contains only the core application services
# Storage (Redis, PostgreSQL) are defined in docker-compose.storage.yml
# Observability stack is defined in docker-compose.observability.yml

services:
  # =================================
  # CORE APPLICATION SERVICES
  # =================================

  rtsp-capture:
    image: ghcr.io/hretheum/detektr/rtsp-capture:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: rtsp-capture
      PORT: 8080
      RTSP_URL: ${RTSP_URL:-rtsp://localhost:8554/stream}
      FRAME_BUFFER_SIZE: ${FRAME_BUFFER_SIZE:-100}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  frame-buffer-v2-v2:
    image: ghcr.io/hretheum/detektr/frame-buffer-v2-v2:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      SERVICE_NAME: frame-buffer-v2-v2
      PORT: 8002
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      FRAME_QUEUE_NAME: ${FRAME_QUEUE_NAME:-frame_queue}
      DLQ_NAME: ${DLQ_NAME:-frame_dlq}
      MAX_BUFFER_SIZE: ${MAX_BUFFER_SIZE:-1000}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  # frame-tracking - removed: this is a library, not a service
  # Frame tracking functionality is provided as a library that other services import
  # See: services/shared/frame-tracking/README.md

  metadata-storage:
    image: ghcr.io/hretheum/detektr/metadata-storage:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      SERVICE_NAME: metadata-storage
      PORT: 8005
      DATABASE_URL: postgresql://${POSTGRES_USER:-detektor}:${POSTGRES_PASSWORD:-detektor_pass}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-detektor_db}
      POSTGRES_USER: ${POSTGRES_USER:-detektor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-detektor_pass}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-detektor_db}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - postgres

  frame-events:
    image: ghcr.io/hretheum/detektr/frame-events:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SERVICE_NAME: frame-events
      PORT: 8081
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-detektor}
      POSTGRES_USER: ${POSTGRES_USER:-detektor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DETEKTOR_DB_PASSWORD: ${POSTGRES_PASSWORD}
      ENABLE_METRICS: "true"
      ENABLE_TRACING: "true"
      OTEL_SERVICE_NAME: frame-events
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
      - jaeger

  # =================================
  # EXAMPLE & DEMO SERVICES
  # =================================

  sample-processor:
    image: ghcr.io/hretheum/detektr/sample-processor:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8099:8099"
    environment:
      SERVICE_NAME: sample-processor
      PROCESSOR_NAME: sample-processor
      PORT: 8099
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      ENABLE_METRICS: "true"
      ENABLE_TRACING: "true"
      OTEL_SERVICE_NAME: sample-processor
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
      CPU_CORES: ${CPU_CORES:-2}
      MEMORY_LIMIT_MB: ${MEMORY_LIMIT_MB:-1024}
      PREFER_GPU: ${PREFER_GPU:-false}
      CONFIDENCE_THRESHOLD: ${CONFIDENCE_THRESHOLD:-0.7}
      BATCH_SIZE: ${BATCH_SIZE:-4}
      PROCESSING_DELAY_MS: ${PROCESSING_DELAY_MS:-50}
      ENABLE_FRAME_CONSUMER: "true"
      FRAME_BUFFER_URL: ${FRAME_BUFFER_URL:-http://frame-buffer-v2:8002}
      CONSUMER_BATCH_SIZE: ${CONSUMER_BATCH_SIZE:-10}
      POLL_INTERVAL_MS: ${POLL_INTERVAL_MS:-100}
      MAX_RETRIES: ${MAX_RETRIES:-3}
      BACKOFF_MS: ${BACKOFF_MS:-1000}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - jaeger
      - frame-buffer-v2

  example-otel:
    image: ghcr.io/hretheum/detektr/example-otel:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8009:8000"
    environment:
      SERVICE_NAME: example-otel
      PORT: 8000
      OTEL_SERVICE_NAME: example-otel
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    profiles:
      - examples

  echo-service:
    image: ghcr.io/hretheum/detektr/echo-service:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8007:8007"
    environment:
      SERVICE_NAME: echo-service
      PORT: 8007
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    profiles:
      - examples

networks:
  detektor-network:
    name: detektor-network
    driver: bridge
