# Frame Events Service - Event Sourcing for Frame Lifecycle
# This service provides audit trail and event sourcing capabilities
# It is NOT the frame-tracking library (which is in services/shared/frame-tracking)

services:
  frame-events:
    image: ghcr.io/hretheum/detektr/frame-events:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SERVICE_NAME: frame-events
      PORT: 8081
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-detektor}
      POSTGRES_USER: ${POSTGRES_USER:-detektor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DETEKTOR_DB_PASSWORD: ${POSTGRES_PASSWORD}
      ENABLE_METRICS: "true"
      ENABLE_TRACING: "true"
      OTEL_SERVICE_NAME: frame-events
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
      - jaeger

networks:
  detektor-network:
    external: true
