codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  
ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "src/interfaces/cli/**/*"  # CLI code often hard to test
  - "src/contexts/*/infrastructure/migrations/**/*"  # DB migrations