# RTSP Capture Service Configuration
# This file extends docker-compose.yml for RTSP service deployment
# Uses pre-built images from GitHub Container Registry

services:
  rtsp-capture:
    image: ghcr.io/hretheum/bezrobocie-detektor/rtsp-capture:latest
    container_name: rtsp-capture
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - RTSP_URL=${RTSP_URL:-rtsp://localhost:8554/stream}
      - RTSP_RECONNECT_TIMEOUT=${RTSP_RECONNECT_TIMEOUT:-5}
      - RTSP_BUFFER_SIZE=${RTSP_BUFFER_SIZE:-100}
      - RTSP_FPS=${RTSP_FPS:-10}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - POSTGRES_URL=${DATABASE_URL:-postgresql://detektor:detektor@postgres:5432/detektor}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:14268/api/traces}
      - OTEL_SERVICE_NAME=rtsp-capture
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=production
    depends_on:
      - redis
      - postgres
      - jaeger
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

networks:
  detektor-network:
    external: true
