version: '3.8'

x-common-variables: &common-variables
  REDIS_HOST: redis
  REDIS_PORT: 6379
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces

x-common-service: &common-service
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  environment:
    <<: *common-variables
  networks:
    - detektor-network
  depends_on:
    - redis

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Example service configuration
  api:
    <<: *common-service
    ports:
      - "8000:8000"
    environment:
      <<: *common-variables
      SERVICE_NAME: api
      PORT: 8000
    command: ["python", "-m", "src.interfaces.api"]

volumes:
  redis-data:

networks:
  detektor-network:
    driver: bridge