# Legacy docker-compose.yml - DEPRECATED
# Please use the new hierarchical structure in docker/ directory
# See docker/README.md for migration instructions
#
# For new deployments, use: ./docker/dev.sh or ./docker/prod.sh
#
# This file is kept for backward compatibility only and will be removed in future versions.
# It simply redirects to the new structure by using Docker Compose v2.20+ include feature.

version: "3.8"

# Include the new hierarchical structure
include:
  - path: docker/base/docker-compose.yml
  - path: docker/base/docker-compose.storage.yml
# Note: If you need observability stack, add:
# - path: docker/base/docker-compose.observability.yml
#
# For development overrides, use:
# docker-compose -f docker/base/docker-compose.yml -f docker/base/docker-compose.storage.yml -f docker/environments/development/docker-compose.override.yml up
