# Redis High Availability Setup with Sentinel
# This replaces the single Redis instance with Master-Slave + Sentinel

services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis-master.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - detektor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-slave:
    image: redis:7-alpine
    container_name: redis-slave
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./config/redis-slave.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-slave-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis-master 6379
    networks:
      - detektor-network
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  sentinel-1:
    image: redis:7-alpine
    container_name: sentinel-1
    restart: unless-stopped
    ports:
      - "26379:26379"
    volumes:
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - sentinel-1-data:/tmp
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - detektor-network
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  sentinel-2:
    image: redis:7-alpine
    container_name: sentinel-2
    restart: unless-stopped
    ports:
      - "26380:26379"
    volumes:
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - sentinel-2-data:/tmp
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - detektor-network
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  sentinel-3:
    image: redis:7-alpine
    container_name: sentinel-3
    restart: unless-stopped
    ports:
      - "26381:26379"
    volumes:
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - sentinel-3-data:/tmp
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - detektor-network
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  redis-master-data:
  redis-slave-data:
  sentinel-1-data:
  sentinel-2-data:
  sentinel-3-data:

networks:
  detektor-network:
    external: true
