global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # Enable exemplar storage
  external_labels:
    monitor: "detektor-monitor"
    environment: "development"

# Load alert rules
rule_files:
  - "alerts/*.yml"

# Storage configuration for exemplars
storage:
  exemplars:
    max_exemplars: 100000

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "detektor-services"
    # Enable exemplar collection
    enable_exemplars: true
    static_configs:
      - targets:
          - "rtsp-capture:8000"
          - "face-recognition:8001"
          - "object-detection:8002"
          - "gesture-detection:8003"
          - "automation-engine:8004"
        labels:
          environment: "production"
    # Relabel to extract service name
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: service_name
        replacement: "$1"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
