services:
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: detektor-redis-exporter
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_EXPORTER_LOG_FORMAT: json
    networks:
      - detektor-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9121/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis

networks:
  detektor-network:
    external: true
