global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "detektor"
    environment: "${ENVIRONMENT:-production}"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Application services
  - job_name: "detektor-services"
    static_configs:
      - targets:
          - "rtsp-capture:8080"
          - "frame-events:8081"
          - "frame-buffer:8002"
          - "face-recognition:8006"
          - "object-detection:8003"
          - "metadata-storage:8005"
          - "echo-service:8007"
          - "gpu-demo:8008"
          - "example-otel:8009"
          - "base-template:8000"
          - "sample-processor:8099"
          - "llm-intent:8010"
          - "gesture-detection:8011"
          - "audio-analysis:8012"
          - "scene-understanding:8013"
          - "ha-bridge:8004"
          - "telegram-alerts:8015"
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: service
        replacement: "$1"

  # Storage exporters
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Infrastructure monitoring
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # GPU monitoring
  - job_name: "nvidia-gpu"
    static_configs:
      - targets: ["nvidia-gpu-exporter:9445"]

  # Jaeger metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
