name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff.toml
          args: --latest --strip header

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') }}

  docker-release:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker images
        run: |
          # Build all services defined in docker-compose
          docker-compose build

          # Tag and push with version
          VERSION=${GITHUB_REF#refs/tags/}
          for service in $(docker-compose config --services); do
            docker tag detektor-$service:latest ghcr.io/${{ github.repository }}/$service:$VERSION
            docker push ghcr.io/${{ github.repository }}/$service:$VERSION
          done

  python-packages:
    name: Build and Publish Python Packages
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build base-processor package
        run: |
          cd services/shared/base-processor
          python -m build

      - name: Check package
        run: |
          cd services/shared/base-processor
          twine check dist/*

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # GitHub Packages PyPI registry is not yet fully supported
          # For now, we'll create a GitHub Release asset
          cd services/shared/base-processor
          for file in dist/*; do
            echo "Uploading $file as release asset..."
            gh release upload "${GITHUB_REF#refs/tags/}" "$file" || true
          done

      - name: Create package metadata
        run: |
          cd services/shared/base-processor
          cat > package-metadata.json << EOF
          {
            "name": "base-processor",
            "version": "${GITHUB_REF#refs/tags/v}",
            "description": "Base processor framework for AI services",
            "python_requires": ">=3.11",
            "install_command": "pip install https://github.com/${{ github.repository }}/releases/download/${GITHUB_REF#refs/tags/}/base_processor-${GITHUB_REF#refs/tags/v}-py3-none-any.whl"
          }
          EOF
          gh release upload "${GITHUB_REF#refs/tags/}" package-metadata.json || true

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mkdocs
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Build documentation
        run: mkdocs build || echo "No mkdocs.yml found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
