name: RTSP Capture Build & Deploy

on:
  push:
    branches: [main]
    paths:
      - 'services/rtsp-capture/**'
      - '.github/workflows/rtsp-capture-deploy.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hretheum/bezrobocie-detektor/rtsp-capture

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: services/rtsp-capture
        file: services/rtsp-capture/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    name: Deploy on Nebula
    runs-on: self-hosted
    needs: build-and-push
    if: github.event_name == 'push'

    steps:
    - name: Deploy
      run: |
        cd /opt/detektor
        docker compose pull rtsp-capture
        docker compose up -d rtsp-capture

    - name: Health check
      run: |
        sleep 10
        curl -f http://localhost:8001/health || exit 1
