name: Security Scan (Disabled)

# Disabled due to permission issues with SARIF upload
# This workflow can be re-enabled when repository permissions are fixed

on:
  workflow_dispatch:  # Only manual trigger to prevent automatic runs

jobs:
  disabled-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "⚠️ Security scan is currently disabled"
          echo "To re-enable:"
          echo "1. Fix repository permissions for SARIF upload"
          echo "2. Uncomment the actual security scan job"
          echo "3. Change trigger from workflow_dispatch to push/pull_request"

# Original workflow (to be restored):
# jobs:
#   security:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Security scan
#       uses: aquasecurity/trivy-action@master
#       with:
#         image-ref: 'ghcr.io/hretheum/detektr/rtsp-capture:latest'
#         format: 'table'
#         exit-code: '0'
