# Disabled due to permission issues with SARIF upload
# This workflow can be re-enabled when repository permissions are fixed
#
# name: Security Scan
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#
# jobs:
#   security:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Security scan
#       uses: aquasecurity/trivy-action@master
#       with:
#         image-ref: 'ghcr.io/hretheum/bezrobocie-detektor/rtsp-capture:latest'
#         format: 'table'
#         exit-code: '0'
