name: Test Self-hosted Runner

on:
  workflow_dispatch:
    inputs:
      runner_label:
        description: 'Runner label to test'
        required: true
        default: 'self-hosted'
        type: choice
        options:
          - 'self-hosted'
          - 'nebula'
          - 'self-hosted,nebula'

jobs:
  test-basic:
    name: Test Basic Connectivity
    runs-on: ${{ github.event.inputs.runner_label }}
    steps:
      - name: Runner Info
        run: |
          echo "🏃 Runner Test Started"
          echo "Runner name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner arch: ${{ runner.arch }}"
          echo "Runner temp: ${{ runner.temp }}"

      - name: System Info
        run: |
          echo "=== System Information ==="
          uname -a
          echo ""
          echo "=== CPU Info ==="
          lscpu | head -10
          echo ""
          echo "=== Memory Info ==="
          free -h
          echo ""
          echo "=== Disk Info ==="
          df -h

      - name: Network Test
        run: |
          echo "=== Network Connectivity ==="
          echo "GitHub API:"
          curl -I https://api.github.com
          echo ""
          echo "GitHub Container Registry:"
          curl -I https://ghcr.io
          echo ""
          echo "Local network:"
          ip addr show

      - name: Docker Test
        run: |
          echo "=== Docker Test ==="
          docker --version
          docker compose version
          echo ""
          echo "Docker info:"
          docker system info | head -20
          echo ""
          echo "Docker images:"
          docker images

      - name: Tools Check
        run: |
          echo "=== Installed Tools ==="
          echo -n "Git: " && git --version
          echo -n "SOPS: " && sops --version || echo "Not installed"
          echo -n "Age: " && age --version || echo "Not installed"
          echo -n "SSH: " && ssh -V
          echo -n "Curl: " && curl --version | head -1

      - name: SSH Test (if configured)
        env:
          NEBULA_HOST: ${{ secrets.NEBULA_HOST }}
          NEBULA_USER: ${{ secrets.NEBULA_USER }}
        run: |
          echo "=== SSH Connectivity Test ==="
          if [[ -n "${NEBULA_HOST}" ]] && [[ -n "${NEBULA_USER}" ]]; then
            echo "Testing SSH to ${NEBULA_USER}@${NEBULA_HOST}..."
            ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no "${NEBULA_USER}@${NEBULA_HOST}" "echo 'SSH connection successful'" || echo "SSH connection failed"
          else
            echo "NEBULA_HOST or NEBULA_USER not configured"
          fi

      - name: Summary
        run: |
          echo ""
          echo "✅ Self-hosted runner is operational!"
          echo "Ready for deployment workflows."
